### ISSUE TITLE
Is there of making commandbox-fusionreactor a dependency in the box.json file?

### ISSUE THREAD

**Issue by cybersonic** [bdw429s/commandbox-fusionreactor#12]
Since we are packaging everything up in docker , we need a way to install fusion reactor too. Where would this be?

**Comment by bdw429s** [comment]
You can add the FR module to your box.json and use the `box_install` env var on the docker image and it will install the module  It's a little sloppy IMO since the module isn't really a direct dependency of the app, but maybe it is-- depends on how you look at it I guess.  There currently isn't any other standard in place to declare CLI dependencies for your app.  Stuff like `commandbox-dotenv` or `commandbox-hostupdater` fall in the same category.
