### ISSUE TITLE
Incorporation of Debug Libraries

### ISSUE THREAD

**Issue by mjclemente** [bdw429s/commandbox-fusionreactor#13]
The FR Debug Libraries are referenced in a comment at the top of ModuleConfig.cfc (https://intergral-dl.s3.amazonaws.com/FR/FusionReactor-7.0.4/debuglibs-7.0.4.zip).

Is there any plan to incorporate the optional installation of the Debug Libraries in this module? 

I'd be happy to help out with this. I haven't given much thought to the specifics of how it would be handled, but is that something of interest?

Thanks!

**Comment by bdw429s** [comment]
@mjclemente Yes, there have been plans to do this literally for years.  I asked the FR folk 2.5 years ago to start putting a proper FR package on ForgeBox with all the binaries in it.  They finally agreed to do this just a month or so ago, but I haven't seen it pop up yet.  Supposedly the first 8.x would be when they did it, but I think that's out and I haven't heard anything.  

Basically, once they get it on ForgeBox, I can GREATLY simplify the process of checking for new versions (currently hardcoded) and downloading the binaries and caching them by funnelling it all through the built in `install` command just like CFEngines do on `server start`.  Once FR gets a packge on ForgeBox with all the bits that's updated by their build process with new versions, I will refactor this module to use it and

* You'll get new versions immediately based on the semver range you configure
* I'll add in the debug libs since they'll all be in one download
* Half of the logic in the moduleConfig will go away and be replaced with a simple install command.

**Comment by mjclemente** [comment]
Makes sense. I can wait for that. Right now I'm installing the Debug Libs manually. Having FR on ForgeBox would be awesome! Feel free to close this... or leave it open until they add the package.

**Comment by neilwightman-intergral** [comment]
This has been fixed @bdw429s when we added fusionreactor.zip to forgebox.io
